#ifndef STATIC_VARIABLES_H_INCLUDED
#define STATIC_VARIABLES_H_INCLUDED

#define AKEY_PRESSED     0
#define AKEY_RELEASED    1
#define AKEY_UP          2
#define AKEY_DOWN        3

#endif // STATIC_VARIABLES_H_INCLUDED
